# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - taskapi-app

env:
  APP_PATH: backend/taskapi
  PYTHON_VERSION: '3.11'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    defaults:
      run:
        working-directory: ${{ env.APP_PATH }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: backend/taskapi/requirements.txt

      - name: Install dependencies and run Django checks
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python manage.py check
                
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            backend/taskapi/**
            !backend/taskapi/antenv/**
            !backend/taskapi/.env
            !backend/taskapi/db.sqlite3
            !backend/taskapi/**/__pycache__/**
            !backend/taskapi/**/*.pyc

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: release
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'taskapi-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5E348022ECC74A6CADB52F44176BF62C }}
          package: release